export const bikes = [
  {
    id: 1,
    title: "2023 Zero SR/F Electric Motorcycle",
    description:
      "Flagship electric motorcycle with 140 ft-lb of torque, 124 mph top speed, and up to 200 miles of city range. Features connected app integration and customizable ride modes.",
    location: "Austin, TX",
    price: "$21,995",
    image: "https://images.pexels.com/photos/2393816/pexels-photo-2393816.jpeg",
    year: "2023",
    engineSize: "N/A",
    fuelType: "Electric",
    make: "Zero",
    model: "SR/F",
    bikeType: "Sport",
  },
  {
    id: 2,
    title: "2022 Harley-Davidson Road Glide",
    description:
      "Classic American touring motorcycle with iconic styling, powerful Milwaukee-Eight 114 engine, and advanced infotainment system with navigation and Bluetooth connectivity.",
    location: "Dallas, TX",
    price: "$27,430",
    image: "https://images.pexels.com/photos/1413412/pexels-photo-1413412.jpeg",
    year: "2022",
    engineSize: "1868",
    fuelType: "Petrol",
    make: "Harley-Davidson",
    model: "Road Glide",
    bikeType: "Touring",
  },
  {
    id: 3,
    title: "2022 Honda CBR1000RR-R Fireblade",
    description:
      "Track-focused superbike with MotoGP-derived aerodynamics, 215 hp inline-four engine, and comprehensive electronics package including multiple riding modes and traction control.",
    location: "Miami, FL",
    price: "$28,500",
    image: "https://images.pexels.com/photos/2393821/pexels-photo-2393821.jpeg",
    year: "2022",
    engineSize: "1000",
    fuelType: "Petrol",
    make: "Honda",
    model: "CBR1000RR-R",
    bikeType: "Sport",
  },
  {
    id: 4,
    title: "2021 Vespa Elettrica",
    description:
      "Modern electric take on the classic Italian scooter with distinctive styling, 62-mile range, and reverse mode for easy maneuvering. Perfect for urban commuting.",
    location: "New York, NY",
    price: "$7,499",
    image: "https://images.pexels.com/photos/1715185/pexels-photo-1715185.jpeg",
    year: "2021",
    engineSize: "N/A",
    fuelType: "Electric",
    make: "Vespa",
    model: "Elettrica",
    bikeType: "Scooter",
  },
];
