export const cars = [
  {
    id: 1,
    title: "2023 Tesla Model 3 Long Range",
    description:
      "The Tesla Model 3 is an electric four-door sedan with minimalist styling and a high-tech interior featuring a 15-inch touchscreen display that controls nearly all vehicle functions.",
    location: "San Francisco, CA",
    price: "$41,990",
    image: "https://images.pexels.com/photos/9606782/pexels-photo-9606782.jpeg",
    year: "2023",
    mileage: "5,200",
    transmission: "Automatic",
    fuelType: "Electric",
    make: "Tesla",
    model: "Model 3",
    bodyType: "Sedan",
  },
  {
    id: 2,
    title: "2022 BMW X5 xDrive40i",
    description:
      "Luxury midsize SUV with powerful turbocharged engine, premium interior, and advanced technology features including gesture control and a digital instrument cluster.",
    location: "Los Angeles, CA",
    price: "$64,500",
    image: "https://images.pexels.com/photos/1835211/pexels-photo-1835211.jpeg",
    year: "2022",
    mileage: "12,450",
    transmission: "Automatic",
    fuelType: "Petrol",
    make: "BMW",
    model: "X5",
    bodyType: "SUV",
  },
  {
    id: 3,
    title: "2021 Ford Mustang Mach-E",
    description:
      "All-electric SUV inspired by the Mustang's design language, offering exhilarating performance with 0-60 mph in as little as 3.5 seconds (GT version).",
    location: "Seattle, WA",
    price: "$48,700",
    image: "https://images.pexels.com/photos/13009437/pexels-photo-13009437.jpeg",
    year: "2021",
    mileage: "18,750",
    transmission: "Automatic",
    fuelType: "Electric",
    make: "Ford",
    model: "Mustang Mach-E",
    bodyType: "SUV",
  },
  {
    id: 4,
    title: "2022 Honda Civic Touring",
    description:
      "Completely redesigned with a more mature exterior design, upgraded interior materials, and improved technology including a 9-inch touchscreen.",
    location: "Chicago, IL",
    price: "$28,300",
    image: "https://images.pexels.com/photos/1077785/pexels-photo-1077785.jpeg",
    year: "2022",
    mileage: "9,870",
    transmission: "Automatic",
    fuelType: "Petrol",
    make: "Honda",
    model: "Civic",
    bodyType: "Sedan",
  },
];
