export const cities = [
  // Major US Cities
  { id: "new-york", name: "New York", country: "United States", timezone: "America/New_York", offset: -5 },
  {
    id: "los-angeles",
    name: "Los Angeles",
    country: "United States",
    timezone: "America/Los_Angeles",
    offset: -8,
  },
  { id: "chicago", name: "Chicago", country: "United States", timezone: "America/Chicago", offset: -6 },
  { id: "denver", name: "Denver", country: "United States", timezone: "America/Denver", offset: -7 },
  { id: "phoenix", name: "Phoenix", country: "United States", timezone: "America/Phoenix", offset: -7 },
  { id: "miami", name: "Miami", country: "United States", timezone: "America/New_York", offset: -5 },
  { id: "seattle", name: "Seattle", country: "United States", timezone: "America/Los_Angeles", offset: -8 },
  { id: "atlanta", name: "Atlanta", country: "United States", timezone: "America/New_York", offset: -5 },
  {
    id: "las-vegas",
    name: "Las Vegas",
    country: "United States",
    timezone: "America/Los_Angeles",
    offset: -8,
  },
  { id: "honolulu", name: "Honolulu", country: "United States", timezone: "Pacific/Honolulu", offset: -10 },

  // Major European Cities
  { id: "london", name: "London", country: "United Kingdom", timezone: "Europe/London", offset: 0 },
  { id: "paris", name: "Paris", country: "France", timezone: "Europe/Paris", offset: 1 },
  { id: "berlin", name: "Berlin", country: "Germany", timezone: "Europe/Berlin", offset: 1 },
  { id: "rome", name: "Rome", country: "Italy", timezone: "Europe/Rome", offset: 1 },
  { id: "madrid", name: "Madrid", country: "Spain", timezone: "Europe/Madrid", offset: 1 },
  { id: "amsterdam", name: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam", offset: 1 },
  { id: "zurich", name: "Zurich", country: "Switzerland", timezone: "Europe/Zurich", offset: 1 },
  { id: "vienna", name: "Vienna", country: "Austria", timezone: "Europe/Vienna", offset: 1 },
  { id: "stockholm", name: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm", offset: 1 },
  { id: "moscow", name: "Moscow", country: "Russia", timezone: "Europe/Moscow", offset: 3 },
  { id: "istanbul", name: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul", offset: 3 },

  // Asian Cities
  { id: "tokyo", name: "Tokyo", country: "Japan", timezone: "Asia/Tokyo", offset: 9 },
  { id: "seoul", name: "Seoul", country: "South Korea", timezone: "Asia/Seoul", offset: 9 },
  { id: "beijing", name: "Beijing", country: "China", timezone: "Asia/Shanghai", offset: 8 },
  { id: "shanghai", name: "Shanghai", country: "China", timezone: "Asia/Shanghai", offset: 8 },
  { id: "hong-kong", name: "Hong Kong", country: "Hong Kong", timezone: "Asia/Hong_Kong", offset: 8 },
  { id: "singapore", name: "Singapore", country: "Singapore", timezone: "Asia/Singapore", offset: 8 },
  { id: "bangkok", name: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok", offset: 7 },
  { id: "mumbai", name: "Mumbai", country: "India", timezone: "Asia/Kolkata", offset: 5.5 },
  { id: "delhi", name: "Delhi", country: "India", timezone: "Asia/Kolkata", offset: 5.5 },
  { id: "dubai", name: "Dubai", country: "UAE", timezone: "Asia/Dubai", offset: 4 },
  { id: "tehran", name: "Tehran", country: "Iran", timezone: "Asia/Tehran", offset: 3.5 },
  { id: "jakarta", name: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta", offset: 7 },

  // Australian & Oceania Cities
  { id: "sydney", name: "Sydney", country: "Australia", timezone: "Australia/Sydney", offset: 11 },
  { id: "melbourne", name: "Melbourne", country: "Australia", timezone: "Australia/Melbourne", offset: 11 },
  { id: "perth", name: "Perth", country: "Australia", timezone: "Australia/Perth", offset: 8 },
  { id: "auckland", name: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland", offset: 13 },

  // African Cities
  { id: "cairo", name: "Cairo", country: "Egypt", timezone: "Africa/Cairo", offset: 2 },
  { id: "cape-town", name: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg", offset: 2 },
  { id: "lagos", name: "Lagos", country: "Nigeria", timezone: "Africa/Lagos", offset: 1 },
  { id: "nairobi", name: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi", offset: 3 },

  // American Cities
  { id: "toronto", name: "Toronto", country: "Canada", timezone: "America/Toronto", offset: -5 },
  { id: "vancouver", name: "Vancouver", country: "Canada", timezone: "America/Vancouver", offset: -8 },
  { id: "mexico-city", name: "Mexico City", country: "Mexico", timezone: "America/Mexico_City", offset: -6 },
  { id: "sao-paulo", name: "São Paulo", country: "Brazil", timezone: "America/Sao_Paulo", offset: -3 },
  {
    id: "rio-de-janeiro",
    name: "Rio de Janeiro",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
    offset: -3,
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
    offset: -3,
  },
  { id: "lima", name: "Lima", country: "Peru", timezone: "America/Lima", offset: -5 },
  { id: "santiago", name: "Santiago", country: "Chile", timezone: "America/Santiago", offset: -3 },
];

export const weatherCities = [
  { name: "Sydney", country: "Australia", code: "au" },
  { name: "Melbourne", country: "Australia", code: "au" },
  { name: "Brisbane", country: "Australia", code: "au" },
  { name: "Perth", country: "Australia", code: "au" },
  { name: "Adelaide", country: "Australia", code: "au" },
  { name: "Gold Coast", country: "Australia", code: "au" },
  { name: "Canberra", country: "Australia", code: "au" },
  { name: "Newcastle", country: "Australia", code: "au" },
  { name: "Wollongong", country: "Australia", code: "au" },
  { name: "Logan City", country: "Australia", code: "au" },

  { name: "Vienna", country: "Austria", code: "" },
  { name: "Graz", country: "Austria", code: "" },
  { name: "Linz", country: "Austria", code: "" },
  { name: "Salzburg", country: "Austria", code: "" },
  { name: "Innsbruck", country: "Austria", code: "" },
  { name: "Klagenfurt", country: "Austria", code: "" },
  { name: "Wels", country: "Austria", code: "" },
  { name: "Sankt Pölten", country: "Austria", code: "" },
  { name: "Dornbirn", country: "Austria", code: "" },
  { name: "Wiener Neustadt", country: "Austria", code: "" },

  { name: "Manama", country: "Bahrain", code: "bh" },
  { name: "Riffa", country: "Bahrain", code: "bh" },
  { name: "Muharraq", country: "Bahrain", code: "bh" },
  { name: "Hamdan", country: "Bahrain", code: "bh" },
  { name: "Isa Town", country: "Bahrain", code: "bh" },
  { name: "Jidhafs", country: "Bahrain", code: "bh" },
  { name: "Sitra", country: "Bahrain", code: "bh" },
  { name: "Budaiya", country: "Bahrain", code: "bh" },
  { name: "Hidd", country: "Bahrain", code: "bh" },
  { name: "A'ali", country: "Bahrain", code: "bh" },

  { name: "Dhaka", country: "Bangladesh", code: "bd" },
  { name: "Chattogram", country: "Bangladesh", code: "bd" },
  { name: "Khulna", country: "Bangladesh", code: "bd" },
  { name: "Rajshahi", country: "Bangladesh", code: "bd" },
  { name: "Sylhet", country: "Bangladesh", code: "bd" },
  { name: "Barishal", country: "Bangladesh", code: "bd" },
  { name: "Rangpur", country: "Bangladesh", code: "bd" },
  { name: "Comilla", country: "Bangladesh", code: "bd" },

  { name: "Brussels", country: "Belgium", code: "" },
  { name: "Antwerp", country: "Belgium", code: "" },
  { name: "Ghent", country: "Belgium", code: "" },
  { name: "Charleroi", country: "Belgium", code: "" },
  { name: "Liège", country: "Belgium", code: "" },
  { name: "Bruges", country: "Belgium", code: "" },
  { name: "Namur", country: "Belgium", code: "" },
  { name: "Leuven", country: "Belgium", code: "" },
  { name: "Mons", country: "Belgium", code: "" },
  { name: "Aalst", country: "Belgium", code: "" },

  { name: "São Paulo", country: "Brazil", code: "br" },
  { name: "Rio de Janeiro", country: "Brazil", code: "br" },
  { name: "Brasília", country: "Brazil", code: "br" },
  { name: "Salvador", country: "Brazil", code: "br" },
  { name: "Fortaleza", country: "Brazil", code: "br" },
  { name: "Belo Horizonte", country: "Brazil", code: "br" },
  { name: "Manaus", country: "Brazil", code: "br" },
  { name: "Curitiba", country: "Brazil", code: "br" },
  { name: "Recife", country: "Brazil", code: "br" },
  { name: "Porto Alegre", country: "Brazil", code: "br" },
  { name: "Belém", country: "Brazil", code: "br" },
  { name: "Goiânia", country: "Brazil", code: "br" },
  { name: "Guarulhos", country: "Brazil", code: "br" },
  { name: "Campinas", country: "Brazil", code: "br" },
  { name: "São Luís", country: "Brazil", code: "br" },
  { name: "São Gonçalo", country: "Brazil", code: "br" },
  { name: "Campina Grande", country: "Brazil", code: "br" },
  { name: "Juazeiro do Norte", country: "Brazil", code: "br" },
  { name: "Feira de Santana", country: "Brazil", code: "br" },
  { name: "Ribeirão Preto", country: "Brazil", code: "br" },
  { name: "Toronto", country: "Canada", code: "ca" },
  { name: "Montreal", country: "Canada", code: "ca" },
  { name: "Vancouver", country: "Canada", code: "ca" },
  { name: "Calgary", country: "Canada", code: "ca" },
  { name: "Edmonton", country: "Canada", code: "ca" },
  { name: "Ottawa", country: "Canada", code: "ca" },
  { name: "Winnipeg", country: "Canada", code: "ca" },
  { name: "Quebec City", country: "Canada", code: "ca" },
  { name: "Hamilton", country: "Canada", code: "ca" },
  { name: "Kitchener", country: "Canada", code: "ca" },

  { name: "Shanghai", country: "China", code: "cn" },
  { name: "Beijing", country: "China", code: "cn" },
  { name: "Chongqing", country: "China", code: "cn" },
  { name: "Tianjin", country: "China", code: "cn" },
  { name: "Guangzhou", country: "China", code: "cn" },
  { name: "Shenzhen", country: "China", code: "cn" },
  { name: "Wuhan", country: "China", code: "cn" },
  { name: "Chengdu", country: "China", code: "cn" },
  { name: "Nanjing", country: "China", code: "cn" },
  { name: "Xi'an", country: "China", code: "cn" },
  { name: "Shenyang", country: "China", code: "cn" },
  { name: "Hangzhou", country: "China", code: "cn" },
  { name: "Harbin", country: "China", code: "cn" },
  { name: "Qingdao", country: "China", code: "cn" },
  { name: "Dalian", country: "China", code: "cn" },
  { name: "Jinan", country: "China", code: "cn" },
  { name: "Zhengzhou", country: "China", code: "cn" },
  { name: "Kunming", country: "China", code: "cn" },
  { name: "Changsha", country: "China", code: "cn" },
  { name: "Changchun", country: "China", code: "cn" },
  { name: "Ningbo", country: "China", code: "cn" },
  { name: "Fuzhou", country: "China", code: "cn" },
  { name: "Shijiazhuang", country: "China", code: "cn" },
  { name: "Taiyuan", country: "China", code: "cn" },
  { name: "Hefei", country: "China", code: "cn" },
  { name: "Urumqi", country: "China", code: "cn" },
  { name: "Xiamen", country: "China", code: "cn" },
  { name: "Shantou", country: "China", code: "cn" },
  { name: "Nanchang", country: "China", code: "cn" },
  { name: "Wenzhou", country: "China", code: "cn" },

  { name: "Prague", country: "Czech Republic", code: "cz" },
  { name: "Brno", country: "Czech Republic", code: "cz" },
  { name: "Ostrava", country: "Czech Republic", code: "cz" },
  { name: "Plzeň", country: "Czech Republic", code: "cz" },
  { name: "Liberec", country: "Czech Republic", code: "cz" },
  { name: "Olomouc", country: "Czech Republic", code: "cz" },
  { name: "Ústí nad Labem", country: "Czech Republic", code: "cz" },
  { name: "Hradec Králové", country: "Czech Republic", code: "cz" },
  { name: "Pardubice", country: "Czech Republic", code: "cz" },
  { name: "Zlín", country: "Czech Republic", code: "cz" },

  { name: "Copenhagen", country: "Denmark", code: "dk" },
  { name: "Aarhus", country: "Denmark", code: "dk" },
  { name: "Odense", country: "Denmark", code: "dk" },
  { name: "Aalborg", country: "Denmark", code: "dk" },
  { name: "Esbjerg", country: "Denmark", code: "dk" },
  { name: "Randers", country: "Denmark", code: "dk" },
  { name: "Kolding", country: "Denmark", code: "dk" },
  { name: "Horsens", country: "Denmark", code: "dk" },
  { name: "Vejle", country: "Denmark", code: "dk" },
  { name: "Roskilde", country: "Denmark", code: "dk" },

  { name: "Cairo", country: "Egypt", code: "eg" },
  { name: "Alexandria", country: "Egypt", code: "eg" },
  { name: "Giza", country: "Egypt", code: "eg" },
  { name: "Shubra El Kheima", country: "Egypt", code: "eg" },
  { name: "Port Said", country: "Egypt", code: "eg" },
  { name: "Suez", country: "Egypt", code: "eg" },
  { name: "Luxor", country: "Egypt", code: "eg" },
  { name: "Tanta", country: "Egypt", code: "eg" },

  { name: "Helsinki", country: "Finland", code: "fi" },
  { name: "Espoo", country: "Finland", code: "fi" },
  { name: "Tampere", country: "Finland", code: "fi" },
  { name: "Vantaa", country: "Finland", code: "fi" },
  { name: "Oulu", country: "Finland", code: "fi" },
  { name: "Turku", country: "Finland", code: "fi" },
  { name: "Jyväskylä", country: "Finland", code: "fi" },
  { name: "Lahti", country: "Finland", code: "fi" },
  { name: "Kuopio", country: "Finland", code: "fi" },
  { name: "Pori", country: "Finland", code: "fi" },

  { name: "Paris", country: "France", code: "fr" },
  { name: "Marseille", country: "France", code: "fr" },
  { name: "Lyon", country: "France", code: "fr" },
  { name: "Toulouse", country: "France", code: "fr" },
  { name: "Nice", country: "France", code: "fr" },
  { name: "Nantes", country: "France", code: "fr" },
  { name: "Strasbourg", country: "France", code: "fr" },
  { name: "Montpellier", country: "France", code: "fr" },
  { name: "Bordeaux", country: "France", code: "fr" },
  { name: "Lille", country: "France", code: "fr" },

  { name: "Berlin", country: "Germany", code: "de" },
  { name: "Hamburg", country: "Germany", code: "de" },
  { name: "Munich", country: "Germany", code: "de" },
  { name: "Cologne", country: "Germany", code: "de" },
  { name: "Frankfurt", country: "Germany", code: "de" },
  { name: "Stuttgart", country: "Germany", code: "de" },
  { name: "Düsseldorf", country: "Germany", code: "de" },
  { name: "Dortmund", country: "Germany", code: "de" },
  { name: "Essen", country: "Germany", code: "de" },
  { name: "Leipzig", country: "Germany", code: "de" },

  { name: "Athens", country: "Greece", code: "gr" },
  { name: "Thessaloniki", country: "Greece", code: "gr" },
  { name: "Patras", country: "Greece", code: "gr" },
  { name: "Heraklion", country: "Greece", code: "gr" },
  { name: "Larissa", country: "Greece", code: "gr" },
  { name: "Volos", country: "Greece", code: "gr" },
  { name: "Ioannina", country: "Greece", code: "gr" },
  { name: "Kalamata", country: "Greece", code: "gr" },
  { name: "Serres", country: "Greece", code: "gr" },
  { name: "Chania", country: "Greece", code: "gr" },

  { name: "Budapest", country: "Hungary", code: "hu" },
  { name: "Debrecen", country: "Hungary", code: "hu" },
  { name: "Szeged", country: "Hungary", code: "hu" },
  { name: "Miskolc", country: "Hungary", code: "hu" },
  { name: "Pécs", country: "Hungary", code: "hu" },
  { name: "Győr", country: "Hungary", code: "hu" },
  { name: "Nyíregyháza", country: "Hungary", code: "hu" },
  { name: "Kecskemét", country: "Hungary", code: "hu" },
  { name: "Székesfehérvár", country: "Hungary", code: "hu" },
  { name: "Szombathely", country: "Hungary", code: "hu" },

  { name: "Delhi", country: "India", code: "in" },
  { name: "Mumbai", country: "India", code: "in" },
  { name: "Bengaluru", country: "India", code: "in" },
  { name: "Kolkata", country: "India", code: "in" },
  { name: "Chennai", country: "India", code: "in" },
  { name: "Hyderabad", country: "India", code: "in" },
  { name: "Pune", country: "India", code: "in" },
  { name: "Ahmedabad", country: "India", code: "in" },
  { name: "Surat", country: "India", code: "in" },
  { name: "Jaipur", country: "India", code: "in" },
  { name: "Lucknow", country: "India", code: "in" },
  { name: "Kanpur", country: "India", code: "in" },
  { name: "Nagpur", country: "India", code: "in" },
  { name: "Indore", country: "India", code: "in" },
  { name: "Thane", country: "India", code: "in" },
  { name: "Bhopal", country: "India", code: "in" },
  { name: "Visakhapatnam", country: "India", code: "in" },
  { name: "Pimpri-Chinchwad", country: "India", code: "in" },
  { name: "Patna", country: "India", code: "in" },
  { name: "Vadodara", country: "India", code: "in" },
  { name: "Ghaziabad", country: "India", code: "in" },
  { name: "Ludhiana", country: "India", code: "in" },
  { name: "Agra", country: "India", code: "in" },
  { name: "Nashik", country: "India", code: "in" },
  { name: "Faridabad", country: "India", code: "in" },
  { name: "Meerut", country: "India", code: "in" },
  { name: "Rajkot", country: "India", code: "in" },
  { name: "Kalyan-Dombivali", country: "India", code: "in" },
  { name: "Vasai-Virar", country: "India", code: "in" },
  { name: "Varanasi", country: "India", code: "in" },
  { name: "Vijayawada", country: "India", code: "in" },
  { name: "Mysore", country: "India", code: "in" },
  { name: "Tiruppur", country: "India", code: "in" },
  { name: "Guwahati", country: "India", code: "in" },
  { name: "Amravati", country: "India", code: "in" },
  { name: "Kolhapur", country: "India", code: "in" },
  { name: "Warangal", country: "India", code: "in" },
  { name: "Tiruchirappalli", country: "India", code: "in" },
  { name: "Salem", country: "India", code: "in" },
  { name: "Srinagar", country: "India", code: "in" },
  { name: "Mangalore", country: "India", code: "in" },

  { name: "Jakarta", country: "Indonesia", code: "id" },
  { name: "Surabaya", country: "Indonesia", code: "id" },
  { name: "Bandung", country: "Indonesia", code: "id" },
  { name: "Medan", country: "Indonesia", code: "id" },
  { name: "Semarang", country: "Indonesia", code: "id" },
  { name: "Palembang", country: "Indonesia", code: "id" },
  { name: "Makassar", country: "Indonesia", code: "id" },
  { name: "Pekanbaru", country: "Indonesia", code: "id" },
  { name: "Batam", country: "Indonesia", code: "id" },
  { name: "Padang", country: "Indonesia", code: "id" },

  { name: "Tehran", country: "Iran", code: "ir" },
  { name: "Mashhad", country: "Iran", code: "ir" },
  { name: "Isfahan", country: "Iran", code: "ir" },
  { name: "Karaj", country: "Iran", code: "ir" },
  { name: "Tabriz", country: "Iran", code: "ir" },
  { name: "Shiraz", country: "Iran", code: "ir" },
  { name: "Qom", country: "Iran", code: "ir" },
  { name: "Ahvaz", country: "Iran", code: "ir" },
  { name: "Kermanshah", country: "Iran", code: "ir" },
  { name: "Orumiyeh", country: "Iran", code: "ir" },

  { name: "Dublin", country: "Ireland", code: "ie" },
  { name: "Cork", country: "Ireland", code: "ie" },
  { name: "Limerick", country: "Ireland", code: "ie" },
  { name: "Galway", country: "Ireland", code: "ie" },
  { name: "Waterford", country: "Ireland", code: "ie" },
  { name: "Drogheda", country: "Ireland", code: "ie" },
  { name: "Swords", country: "Ireland", code: "ie" },
  { name: "Dundalk", country: "Ireland", code: "ie" },
  { name: "Bray", country: "Ireland", code: "ie" },
  { name: "Navan", country: "Ireland", code: "ie" },

  { name: "Jerusalem", country: "Israel", code: "il" },
  { name: "Tel Aviv", country: "Israel", code: "il" },
  { name: "Haifa", country: "Israel", code: "il" },
  { name: "Rishon LeZion", country: "Israel", code: "il" },
  { name: "Petah Tikva", country: "Israel", code: "il" },
  { name: "Ashdod", country: "Israel", code: "il" },
  { name: "Netanya", country: "Israel", code: "il" },
  { name: "Beersheba", country: "Israel", code: "il" },
  { name: "Holon", country: "Israel", code: "il" },
  { name: "Bnei Brak", country: "Israel", code: "il" },

  { name: "Rome", country: "Italy", code: "it" },
  { name: "Milan", country: "Italy", code: "it" },
  { name: "Naples", country: "Italy", code: "it" },
  { name: "Turin", country: "Italy", code: "it" },
  { name: "Palermo", country: "Italy", code: "it" },
  { name: "Genoa", country: "Italy", code: "it" },
  { name: "Bologna", country: "Italy", code: "it" },
  { name: "Florence", country: "Italy", code: "it" },
  { name: "Bari", country: "Italy", code: "it" },
  { name: "Catania", country: "Italy", code: "it" },
  { name: "Tokyo", country: "Japan", code: "jp" },
  { name: "Osaka", country: "Japan", code: "jp" },
  { name: "Nagoya", country: "Japan", code: "jp" },
  { name: "Sapporo", country: "Japan", code: "jp" },
  { name: "Fukuoka", country: "Japan", code: "jp" },
  { name: "Kobe", country: "Japan", code: "jp" },
  { name: "Kyoto", country: "Japan", code: "jp" },
  { name: "Kawasaki", country: "Japan", code: "jp" },
  { name: "Saitama", country: "Japan", code: "jp" },
  { name: "Hiroshima", country: "Japan", code: "jp" },
  { name: "Sendai", country: "Japan", code: "jp" },
  { name: "Kitakyushu", country: "Japan", code: "jp" },
  { name: "Chiba", country: "Japan", code: "jp" },
  { name: "Sakai", country: "Japan", code: "jp" },
  { name: "Niigata", country: "Japan", code: "jp" },

  { name: "Almaty", country: "Kazakhstan", code: "kz" },
  { name: "Nur-Sultan", country: "Kazakhstan", code: "kz" },
  { name: "Shymkent", country: "Kazakhstan", code: "kz" },
  { name: "Karaganda", country: "Kazakhstan", code: "kz" },
  { name: "Taraz", country: "Kazakhstan", code: "kz" },
  { name: "Pavlodar", country: "Kazakhstan", code: "kz" },
  { name: "Oskemen", country: "Kazakhstan", code: "kz" },
  { name: "Semey", country: "Kazakhstan", code: "kz" },
  { name: "Aktobe", country: "Kazakhstan", code: "kz" },
  { name: "Kostanay", country: "Kazakhstan", code: "kz" },

  { name: "Mexico City", country: "Mexico", code: "mx" },
  { name: "Guadalajara", country: "Mexico", code: "mx" },
  { name: "Monterrey", country: "Mexico", code: "mx" },
  { name: "Puebla", country: "Mexico", code: "mx" },
  { name: "Tijuana", country: "Mexico", code: "mx" },
  { name: "León", country: "Mexico", code: "mx" },
  { name: "Juárez", country: "Mexico", code: "mx" },
  { name: "Zapopan", country: "Mexico", code: "mx" },
  { name: "San Luis Potosí", country: "Mexico", code: "mx" },
  { name: "Mérida", country: "Mexico", code: "mx" },
  { name: "Mexicali", country: "Mexico", code: "mx" },
  { name: "Culiacán", country: "Mexico", code: "mx" },
  { name: "Querétaro", country: "Mexico", code: "mx" },
  { name: "Aguascalientes", country: "Mexico", code: "mx" },
  { name: "Hermosillo", country: "Mexico", code: "mx" },
  { name: "Cancún", country: "Mexico", code: "mx" },
  { name: "Veracruz", country: "Mexico", code: "mx" },
  { name: "Acapulco", country: "Mexico", code: "mx" },
  { name: "Toluca", country: "Mexico", code: "mx" },
  { name: "Tampico", country: "Mexico", code: "mx" },

  { name: "Kathmandu", country: "Nepal", code: "np" },
  { name: "Pokhara", country: "Nepal", code: "np" },
  { name: "Lalitpur", country: "Nepal", code: "np" },
  { name: "Biratnagar", country: "Nepal", code: "np" },
  { name: "Birgunj", country: "Nepal", code: "np" },
  { name: "Dharan", country: "Nepal", code: "np" },
  { name: "Bhaktapur", country: "Nepal", code: "np" },
  { name: "Dhangadhi", country: "Nepal", code: "np" },
  { name: "Itahari", country: "Nepal", code: "np" },
  { name: "Janakpur", country: "Nepal", code: "np" },

  { name: "Amsterdam", country: "Netherlands", code: "" },
  { name: "Rotterdam", country: "Netherlands", code: "" },
  { name: "The Hague", country: "Netherlands", code: "" },
  { name: "Utrecht", country: "Netherlands", code: "" },
  { name: "Eindhoven", country: "Netherlands", code: "" },
  { name: "Groningen", country: "Netherlands", code: "" },
  { name: "Tilburg", country: "Netherlands", code: "" },
  { name: "Almere", country: "Netherlands", code: "" },
  { name: "Breda", country: "Netherlands", code: "" },
  { name: "Nijmegen", country: "Netherlands", code: "" },

  { name: "Lagos", country: "Nigeria", code: "ng" },
  { name: "Kano", country: "Nigeria", code: "ng" },
  { name: "Ibadan", country: "Nigeria", code: "ng" },
  { name: "Benin City", country: "Nigeria", code: "ng" },
  { name: "Port Harcourt", country: "Nigeria", code: "ng" },
  { name: "Maiduguri", country: "Nigeria", code: "ng" },
  { name: "Zaria", country: "Nigeria", code: "ng" },
  { name: "Aba", country: "Nigeria", code: "ng" },
  { name: "Jos", country: "Nigeria", code: "ng" },
  { name: "Ilorin", country: "Nigeria", code: "ng" },
  { name: "Oyo", country: "Nigeria", code: "ng" },
  { name: "Enugu", country: "Nigeria", code: "ng" },

  { name: "Oslo", country: "Norway", code: "no" },
  { name: "Bergen", country: "Norway", code: "no" },
  { name: "Trondheim", country: "Norway", code: "no" },
  { name: "Stavanger", country: "Norway", code: "no" },
  { name: "Tromsø", country: "Norway", code: "no" },
  { name: "Drammen", country: "Norway", code: "no" },
  { name: "Fredrikstad", country: "Norway", code: "no" },
  { name: "Porsgrunn", country: "Norway", code: "no" },
  { name: "Skien", country: "Norway", code: "no" },
  { name: "Bodø", country: "Norway", code: "no" },

  { name: "Muscat", country: "Oman", code: "om" },
  { name: "Salalah", country: "Oman", code: "om" },
  { name: "Sohar", country: "Oman", code: "om" },
  { name: "Nizwa", country: "Oman", code: "om" },
  { name: "Sur", country: "Oman", code: "om" },
  { name: "Sultan Qaboos City", country: "Oman", code: "om" },
  { name: "Buraimi", country: "Oman", code: "om" },
  { name: "Seeb", country: "Oman", code: "om" },
  { name: "Ibri", country: "Oman", code: "om" },
  { name: "Rustaq", country: "Oman", code: "om" },
  { name: "Karachi", country: "Pakistan", code: "pk" },
  { name: "Lahore", country: "Pakistan", code: "pk" },
  { name: "Islamabad", country: "Pakistan", code: "pk" },
  { name: "Faisalabad", country: "Pakistan", code: "pk" },
  { name: "Rawalpindi", country: "Pakistan", code: "pk" },
  { name: "Multan", country: "Pakistan", code: "pk" },
  { name: "Peshawar", country: "Pakistan", code: "pk" },
  { name: "Quetta", country: "Pakistan", code: "pk" },
  { name: "Sialkot", country: "Pakistan", code: "pk" },
  { name: "Gujranwala", country: "Pakistan", code: "pk" },
  { name: "Hyderabad", country: "Pakistan", code: "pk" },
  { name: "Sukkur", country: "Pakistan", code: "pk" },
  { name: "Bahawalpur", country: "Pakistan", code: "pk" },
  { name: "Sargodha", country: "Pakistan", code: "pk" },
  { name: "Abbottabad", country: "Pakistan", code: "pk" },
  { name: "Mardan", country: "Pakistan", code: "pk" },
  { name: "Okara", country: "Pakistan", code: "pk" },
  { name: "Khanewal", country: "Pakistan", code: "pk" },
  { name: "Chitral", country: "Pakistan", code: "pk" },
  { name: "Gwadar", country: "Pakistan", code: "pk" },

  { name: "Manila", country: "Philippines", code: "ph" },
  { name: "Quezon City", country: "Philippines", code: "ph" },
  { name: "Caloocan", country: "Philippines", code: "ph" },
  { name: "Davao City", country: "Philippines", code: "ph" },
  { name: "Cebu City", country: "Philippines", code: "ph" },
  { name: "Zamboanga City", country: "Philippines", code: "ph" },
  { name: "Antipolo", country: "Philippines", code: "ph" },
  { name: "Pasig", country: "Philippines", code: "ph" },
  { name: "Taguig", country: "Philippines", code: "ph" },
  { name: "Cagayan de Oro", country: "Philippines", code: "ph" },

  { name: "Warsaw", country: "Poland", code: "pl" },
  { name: "Kraków", country: "Poland", code: "pl" },
  { name: "Łódź", country: "Poland", code: "pl" },
  { name: "Wrocław", country: "Poland", code: "pl" },
  { name: "Poznań", country: "Poland", code: "pl" },
  { name: "Gdańsk", country: "Poland", code: "pl" },
  { name: "Szczecin", country: "Poland", code: "pl" },
  { name: "Bydgoszcz", country: "Poland", code: "pl" },
  { name: "Lublin", country: "Poland", code: "pl" },
  { name: "Katowice", country: "Poland", code: "pl" },

  { name: "Lisbon", country: "Portugal", code: "pt" },
  { name: "Porto", country: "Portugal", code: "pt" },
  { name: "Braga", country: "Portugal", code: "pt" },
  { name: "Coimbra", country: "Portugal", code: "pt" },
  { name: "Faro", country: "Portugal", code: "pt" },
  { name: "Setúbal", country: "Portugal", code: "pt" },
  { name: "Viseu", country: "Portugal", code: "pt" },
  { name: "Aveiro", country: "Portugal", code: "pt" },
  { name: "Leiria", country: "Portugal", code: "pt" },
  { name: "Évora", country: "Portugal", code: "pt" },

  { name: "Doha", country: "Qatar", code: "qa" },
  { name: "Al Rayyan", country: "Qatar", code: "qa" },
  { name: "Umm Salal", country: "Qatar", code: "qa" },
  { name: "Al Wakrah", country: "Qatar", code: "qa" },
  { name: "Dukhan", country: "Qatar", code: "qa" },
  { name: "Al Khor", country: "Qatar", code: "qa" },
  { name: "Mesaieed", country: "Qatar", code: "qa" },
  { name: "Al Shamal", country: "Qatar", code: "qa" },
  { name: "Madinat ash Shamal", country: "Qatar", code: "qa" },
  { name: "Al Ruwais", country: "Qatar", code: "qa" },

  { name: "Bucharest", country: "Romania", code: "ro" },
  { name: "Cluj-Napoca", country: "Romania", code: "ro" },
  { name: "Timișoara", country: "Romania", code: "ro" },
  { name: "Iași", country: "Romania", code: "ro" },
  { name: "Constanța", country: "Romania", code: "ro" },
  { name: "Craiova", country: "Romania", code: "ro" },
  { name: "Brașov", country: "Romania", code: "ro" },
  { name: "Galați", country: "Romania", code: "ro" },
  { name: "Ploiești", country: "Romania", code: "ro" },
  { name: "Oradea", country: "Romania", code: "ro" },

  { name: "Moscow", country: "Russia", code: "ru" },
  { name: "Saint Petersburg", country: "Russia", code: "ru" },
  { name: "Novosibirsk", country: "Russia", code: "ru" },
  { name: "Yekaterinburg", country: "Russia", code: "ru" },
  { name: "Nizhny Novgorod", country: "Russia", code: "ru" },
  { name: "Kazan", country: "Russia", code: "ru" },
  { name: "Chelyabinsk", country: "Russia", code: "ru" },
  { name: "Omsk", country: "Russia", code: "ru" },
  { name: "Samara", country: "Russia", code: "ru" },
  { name: "Rostov-on-Don", country: "Russia", code: "ru" },
  { name: "Ufa", country: "Russia", code: "ru" },
  { name: "Krasnoyarsk", country: "Russia", code: "ru" },
  { name: "Perm", country: "Russia", code: "ru" },
  { name: "Voronezh", country: "Russia", code: "ru" },
  { name: "Volgograd", country: "Russia", code: "ru" },

  { name: "Riyadh", country: "Saudi Arabia", code: "sa" },
  { name: "Jeddah", country: "Saudi Arabia", code: "sa" },
  { name: "Mecca", country: "Saudi Arabia", code: "sa" },
  { name: "Medina", country: "Saudi Arabia", code: "sa" },
  { name: "Dammam", country: "Saudi Arabia", code: "sa" },
  { name: "Ta'if", country: "Saudi Arabia", code: "sa" },
  { name: "Tabuk", country: "Saudi Arabia", code: "sa" },
  { name: "Buraidah", country: "Saudi Arabia", code: "sa" },
  { name: "Khamis Mushait", country: "Saudi Arabia", code: "sa" },
  { name: "Hafar Al-Batin", country: "Saudi Arabia", code: "sa" },

  { name: "Johannesburg", country: "South Africa", code: "za" },
  { name: "Cape Town", country: "South Africa", code: "za" },
  { name: "Durban", country: "South Africa", code: "za" },
  { name: "Pretoria", country: "South Africa", code: "za" },
  { name: "Port Elizabeth", country: "South Africa", code: "za" },
  { name: "Bloemfontein", country: "South Africa", code: "za" },
  { name: "Nelspruit", country: "South Africa", code: "za" },
  { name: "Pietermaritzburg", country: "South Africa", code: "za" },
  { name: "East London", country: "South Africa", code: "za" },
  { name: "Kimberley", country: "South Africa", code: "za" },
  { name: "Madrid", country: "Spain", code: "es" },
  { name: "Barcelona", country: "Spain", code: "es" },
  { name: "Valencia", country: "Spain", code: "es" },
  { name: "Seville", country: "Spain", code: "es" },
  { name: "Zaragoza", country: "Spain", code: "es" },
  { name: "Málaga", country: "Spain", code: "es" },
  { name: "Murcia", country: "Spain", code: "es" },
  { name: "Palma", country: "Spain", code: "es" },
  { name: "Las Palmas", country: "Spain", code: "es" },
  { name: "Bilbao", country: "Spain", code: "es" },

  { name: "Colombo", country: "Sri Lanka", code: "lk" },
  { name: "Kandy", country: "Sri Lanka", code: "lk" },
  { name: "Galle", country: "Sri Lanka", code: "lk" },
  { name: "Jaffna", country: "Sri Lanka", code: "lk" },
  { name: "Negombo", country: "Sri Lanka", code: "lk" },
  { name: "Ratnapura", country: "Sri Lanka", code: "lk" },
  { name: "Batticaloa", country: "Sri Lanka", code: "lk" },
  { name: "Trincomalee", country: "Sri Lanka", code: "lk" },
  { name: "Anuradhapura", country: "Sri Lanka", code: "lk" },
  { name: "Badulla", country: "Sri Lanka", code: "lk" },

  { name: "Stockholm", country: "Sweden", code: "se" },
  { name: "Gothenburg", country: "Sweden", code: "se" },
  { name: "Malmö", country: "Sweden", code: "se" },
  { name: "Uppsala", country: "Sweden", code: "se" },
  { name: "Västerås", country: "Sweden", code: "se" },
  { name: "Örebro", country: "Sweden", code: "se" },
  { name: "Linköping", country: "Sweden", code: "se" },
  { name: "Helsingborg", country: "Sweden", code: "se" },
  { name: "Jönköping", country: "Sweden", code: "se" },
  { name: "Norrköping", country: "Sweden", code: "se" },

  { name: "Zurich", country: "Switzerland", code: "ch" },
  { name: "Geneva", country: "Switzerland", code: "ch" },
  { name: "Basel", country: "Switzerland", code: "ch" },
  { name: "Bern", country: "Switzerland", code: "ch" },
  { name: "Lausanne", country: "Switzerland", code: "ch" },
  { name: "Winterthur", country: "Switzerland", code: "ch" },
  { name: "Lucerne", country: "Switzerland", code: "ch" },
  { name: "St. Gallen", country: "Switzerland", code: "ch" },
  { name: "Lugano", country: "Switzerland", code: "ch" },
  { name: "Biel/Bienne", country: "Switzerland", code: "ch" },
  { name: "Istanbul", country: "Turkey", code: "tr" },
  { name: "Ankara", country: "Turkey", code: "tr" },
  { name: "İzmir", country: "Turkey", code: "tr" },
  { name: "Bursa", country: "Turkey", code: "tr" },
  { name: "Antalya", country: "Turkey", code: "tr" },
  { name: "Adana", country: "Turkey", code: "tr" },
  { name: "Konya", country: "Turkey", code: "tr" },
  { name: "Gaziantep", country: "Turkey", code: "tr" },
  { name: "Kayseri", country: "Turkey", code: "tr" },
  { name: "Mersin", country: "Turkey", code: "tr" },

  { name: "Dubai", country: "United Arab Emirates", code: "ae" },
  { name: "Abu Dhabi", country: "United Arab Emirates", code: "ae" },
  { name: "Sharjah", country: "United Arab Emirates", code: "ae" },
  { name: "Al Ain", country: "United Arab Emirates", code: "ae" },
  { name: "Ajman", country: "United Arab Emirates", code: "ae" },
  { name: "Ras Al Khaimah", country: "United Arab Emirates", code: "ae" },
  { name: "Fujairah", country: "United Arab Emirates", code: "ae" },
  { name: "Umm Al Quwain", country: "United Arab Emirates", code: "ae" },
  { name: "Khor Fakkan", country: "United Arab Emirates", code: "ae" },
  { name: "Dibba Al-Fujairah", country: "United Arab Emirates", code: "ae" },

  { name: "Kyiv", country: "Ukraine", code: "ua" },
  { name: "Kharkiv", country: "Ukraine", code: "ua" },
  { name: "Odesa", country: "Ukraine", code: "ua" },
  { name: "Dnipro", country: "Ukraine", code: "ua" },
  { name: "Donetsk", country: "Ukraine", code: "ua" },
  { name: "Zaporizhzhia", country: "Ukraine", code: "ua" },
  { name: "Lviv", country: "Ukraine", code: "ua" },
  { name: "Kryvyi Rih", country: "Ukraine", code: "ua" },
  { name: "Mykolaiv", country: "Ukraine", code: "ua" },
  { name: "Mariupol", country: "Ukraine", code: "ua" },

  { name: "London", country: "United Kingdom", code: "uk" },
  { name: "Birmingham", country: "United Kingdom", code: "uk" },
  { name: "Glasgow", country: "United Kingdom", code: "uk" },
  { name: "Liverpool", country: "United Kingdom", code: "uk" },
  { name: "Bristol", country: "United Kingdom", code: "uk" },
  { name: "Manchester", country: "United Kingdom", code: "uk" },
  { name: "Sheffield", country: "United Kingdom", code: "uk" },
  { name: "Leeds", country: "United Kingdom", code: "uk" },
  { name: "Edinburgh", country: "United Kingdom", code: "uk" },
  { name: "Leicester", country: "United Kingdom", code: "uk" },

  { name: "New York City", country: "United States", code: "us" },
  { name: "Los Angeles", country: "United States", code: "us" },
  { name: "Chicago", country: "United States", code: "us" },
  { name: "Houston", country: "United States", code: "us" },
  { name: "Phoenix", country: "United States", code: "us" },
  { name: "Philadelphia", country: "United States", code: "us" },
  { name: "San Antonio", country: "United States", code: "us" },
  { name: "San Diego", country: "United States", code: "us" },
  { name: "Dallas", country: "United States", code: "us" },
  { name: "San Jose", country: "United States", code: "us" },
  { name: "Austin", country: "United States", code: "us" },
  { name: "Jacksonville", country: "United States", code: "us" },
  { name: "San Francisco", country: "United States", code: "us" },
  { name: "Columbus", country: "United States", code: "us" },
  { name: "Fort Worth", country: "United States", code: "us" },
  { name: "Indianapolis", country: "United States", code: "us" },
  { name: "Charlotte", country: "United States", code: "us" },
  { name: "Seattle", country: "United States", code: "us" },
  { name: "Denver", country: "United States", code: "us" },
  { name: "El Paso", country: "United States", code: "us" },
  { name: "Detroit", country: "United States", code: "us" },
  { name: "Boston", country: "United States", code: "us" },
  { name: "Memphis", country: "United States", code: "us" },
  { name: "Nashville", country: "United States", code: "us" },
  { name: "Portland", country: "United States", code: "us" },
  { name: "Oklahoma City", country: "United States", code: "us" },
  { name: "Las Vegas", country: "United States", code: "us" },
  { name: "Baltimore", country: "United States", code: "us" },
  { name: "Milwaukee", country: "United States", code: "us" },
  { name: "Albuquerque", country: "United States", code: "us" },
  { name: "Riverside", country: "United States", code: "us" },
  { name: "Bakersfield", country: "United States", code: "us" },
  { name: "Stockton", country: "United States", code: "us" },
  { name: "St Paul", country: "United States", code: "us" },
  { name: "Cincinnati", country: "United States", code: "us" },
  { name: "Pittsburgh", country: "United States", code: "us" },
  { name: "Anchorage", country: "United States", code: "us" },
  { name: "Honolulu", country: "United States", code: "us" },
  { name: "Raleigh", country: "United States", code: "us" },
  { name: "Miami Beach", country: "United States", code: "us" },
  { name: "Tallahassee", country: "United States", code: "us" },

  { name: "Tashkent", country: "Uzbekistan", code: "uz" },
  { name: "Samarkand", country: "Uzbekistan", code: "uz" },
  { name: "Namangan", country: "Uzbekistan", code: "uz" },
  { name: "Andijan", country: "Uzbekistan", code: "uz" },
  { name: "Bukhara", country: "Uzbekistan", code: "uz" },
  { name: "Nukus", country: "Uzbekistan", code: "uz" },
  { name: "Kokand", country: "Uzbekistan", code: "uz" },
  { name: "Ferghana", country: "Uzbekistan", code: "uz" },
  { name: "Margilan", country: "Uzbekistan", code: "uz" },
  { name: "Jizzakh", country: "Uzbekistan", code: "uz" },
];
