// Mock data based on the mongoose schemas
export const mockLeagues = [
  {
    idLeague: "L001",
    idAPIfootball: "API001",
    name: "Premier League",
    alternateName: "English Premier League",
    division: "1",
    isCup: false,
    currentSeason: "2024-25",
    formedYear: "1992",
    firstEventDate: new Date("1992-08-15"),
    gender: "Male",
    country: "England",
    website: "https://premierleague.com",
    facebook: "premierleague",
    instagram: "premierleague",
    twitter: "premierleague",
    youtube: "premierleague",
    description: "The Premier League is the highest level of the English football league system.",
    badge: "https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg",
    logo: "https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
  {
    idLeague: "L002",
    idAPIfootball: "API002",
    name: "La Liga",
    alternateName: "Primera División",
    division: "1",
    isCup: false,
    currentSeason: "2024-25",
    formedYear: "1929",
    firstEventDate: new Date("1929-02-10"),
    gender: "Male",
    country: "Spain",
    website: "https://laliga.com",
    facebook: "laliga",
    instagram: "laliga",
    twitter: "laliga",
    youtube: "laliga",
    description: "La Liga is the top professional football division of the Spanish football league system.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
  {
    idLeague: "L003",
    idAPIfootball: "API003",
    name: "Bundesliga",
    alternateName: "1. Bundesliga",
    division: "1",
    isCup: false,
    currentSeason: "2024-25",
    formedYear: "1963",
    firstEventDate: new Date("1963-08-24"),
    gender: "Male",
    country: "Germany",
    website: "https://bundesliga.com",
    facebook: "bundesliga",
    instagram: "bundesliga",
    twitter: "bundesliga",
    youtube: "bundesliga",
    description: "The Bundesliga is a professional association football league in Germany.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
  {
    idLeague: "L004",
    idAPIfootball: "API004",
    name: "Serie A",
    alternateName: "Serie A TIM",
    division: "1",
    isCup: false,
    currentSeason: "2024-25",
    formedYear: "1898",
    firstEventDate: new Date("1898-05-08"),
    gender: "Male",
    country: "Italy",
    website: "https://legaseriea.it",
    facebook: "seriea",
    instagram: "seriea",
    twitter: "seriea",
    youtube: "seriea",
    description: "Serie A is the top professional football league in Italy.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
  {
    idLeague: "L005",
    idAPIfootball: "API005",
    name: "Ligue 1",
    alternateName: "Ligue 1 Uber Eats",
    division: "1",
    isCup: false,
    currentSeason: "2024-25",
    formedYear: "1932",
    firstEventDate: new Date("1932-09-11"),
    gender: "Male",
    country: "France",
    website: "https://ligue1.com",
    facebook: "ligue1",
    instagram: "ligue1",
    twitter: "ligue1",
    youtube: "ligue1",
    description: "Ligue 1 is the top division of French football.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
  {
    idLeague: "L006",
    idAPIfootball: "API006",
    name: "MLS",
    alternateName: "Major League Soccer",
    division: "1",
    isCup: false,
    currentSeason: "2024",
    formedYear: "1993",
    firstEventDate: new Date("1996-04-06"),
    gender: "Male",
    country: "United States",
    website: "https://mlssoccer.com",
    facebook: "mls",
    instagram: "mls",
    twitter: "mls",
    youtube: "mls",
    description: "Major League Soccer is the top professional soccer league in the United States and Canada.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    trophy: "https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg",
    status: true,
  },
];

export const mockTeams = [
  {
    idTeam: "T001",
    idAPIfootball: "API_T001",
    name: "Manchester United",
    alternateName: "Man United",
    shortName: "MUN",
    formedYear: "1878",
    sport: "Soccer",
    leagues: [
      {
        league: "L001",
        leagueName: "Premier League",
      },
    ],
    stadium: {
      idVenue: "V001",
      name: "Old Trafford",
      location: "Manchester, England",
      capacity: 74310,
    },
    keywords: "Red Devils, Manchester",
    website: "https://manutd.com",
    facebook: "manchesterunited",
    twitter: "manutd",
    instagram: "manchesterunited",
    youtube: "manutd",
    description: "Manchester United Football Club is a professional football club based in Manchester.",
    badge: "https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg",
    logo: "https://images.pexels.com/photos/274506/pexels-photo-274506.jpeg",
    gender: "Male",
    country: "England",
    status: true,
  },
  {
    idTeam: "T002",
    idAPIfootball: "API_T002",
    name: "Real Madrid",
    alternateName: "Real Madrid CF",
    shortName: "RMA",
    formedYear: "1902",
    sport: "Soccer",
    leagues: [
      {
        league: "L002",
        leagueName: "La Liga",
      },
    ],
    stadium: {
      idVenue: "V002",
      name: "Santiago Bernabéu",
      location: "Madrid, Spain",
      capacity: 81044,
    },
    keywords: "Los Blancos, Madrid",
    website: "https://realmadrid.com",
    facebook: "realmadrid",
    twitter: "realmadrid",
    instagram: "realmadrid",
    youtube: "realmadrid",
    description: "Real Madrid Club de Fútbol is a Spanish professional football club based in Madrid.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    gender: "Male",
    country: "Spain",
    status: true,
  },
  {
    idTeam: "T003",
    idAPIfootball: "API_T003",
    name: "Bayern Munich",
    alternateName: "FC Bayern München",
    shortName: "BAY",
    formedYear: "1900",
    sport: "Soccer",
    leagues: [
      {
        league: "L003",
        leagueName: "Bundesliga",
      },
    ],
    stadium: {
      idVenue: "V003",
      name: "Allianz Arena",
      location: "Munich, Germany",
      capacity: 75000,
    },
    keywords: "Die Bayern, Munich",
    website: "https://fcbayern.com",
    facebook: "fcbayern",
    twitter: "fcbayern",
    instagram: "fcbayern",
    youtube: "fcbayern",
    description: "FC Bayern Munich is a German professional sports club based in Munich.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    gender: "Male",
    country: "Germany",
    status: true,
  },
  {
    idTeam: "T004",
    idAPIfootball: "API_T004",
    name: "Juventus",
    alternateName: "Juventus FC",
    shortName: "JUV",
    formedYear: "1897",
    sport: "Soccer",
    leagues: [
      {
        league: "L004",
        leagueName: "Serie A",
      },
    ],
    stadium: {
      idVenue: "V004",
      name: "Allianz Stadium",
      location: "Turin, Italy",
      capacity: 41507,
    },
    keywords: "Juve, Turin",
    website: "https://juventus.com",
    facebook: "juventus",
    twitter: "juventusfc",
    instagram: "juventus",
    youtube: "juventus",
    description: "Juventus Football Club is an Italian professional football club based in Turin.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    gender: "Male",
    country: "Italy",
    status: true,
  },
  {
    idTeam: "T005",
    idAPIfootball: "API_T005",
    name: "Paris Saint-Germain",
    alternateName: "PSG",
    shortName: "PSG",
    formedYear: "1970",
    sport: "Soccer",
    leagues: [
      {
        league: "L005",
        leagueName: "Ligue 1",
      },
    ],
    stadium: {
      idVenue: "V005",
      name: "Parc des Princes",
      location: "Paris, France",
      capacity: 47929,
    },
    keywords: "PSG, Paris",
    website: "https://psg.fr",
    facebook: "psg",
    twitter: "psg_english",
    instagram: "psg",
    youtube: "psg",
    description: "Paris Saint-Germain Football Club is a French professional football club based in Paris.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    gender: "Male",
    country: "France",
    status: true,
  },
  {
    idTeam: "T006",
    idAPIfootball: "API_T006",
    name: "LA Galaxy",
    alternateName: "Los Angeles Galaxy",
    shortName: "LAG",
    formedYear: "1994",
    sport: "Soccer",
    leagues: [
      {
        league: "L006",
        leagueName: "MLS",
      },
    ],
    stadium: {
      idVenue: "V006",
      name: "Dignity Health Sports Park",
      location: "Carson, California",
      capacity: 27000,
    },
    keywords: "Galaxy, Los Angeles",
    website: "https://lagalaxy.com",
    facebook: "lagalaxy",
    twitter: "lagalaxy",
    instagram: "lagalaxy",
    youtube: "lagalaxy",
    description: "LA Galaxy is an American professional soccer club based in Los Angeles.",
    badge: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    logo: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    gender: "Male",
    country: "United States",
    status: true,
  },
];

export const mockPlayers = [
  {
    idPlayer: "P001",
    idAPIfootball: "API_P001",
    name: "Marcus Rashford",
    alternateName: "Marcus Rashford MBE",
    nationality: "England",
    team: "T001",
    sport: "Soccer",
    dateBorn: new Date("1997-10-31"),
    number: "10",
    signing: "2024-06-30",
    birthLocation: "Manchester, England",
    position: "Forward",
    height: "180 cm",
    weight: "70 kg",
    gender: "Male",
    status: "Active",
    description: "English professional footballer who plays as a forward.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "MarcusRashford",
    twitter: "MarcusRashford",
    instagram: "marcusrashford",
  },
  {
    idPlayer: "P002",
    idAPIfootball: "API_P002",
    name: "Karim Benzema",
    alternateName: "Karim Mostafa Benzema",
    nationality: "France",
    team: "T002",
    sport: "Soccer",
    dateBorn: new Date("1987-12-19"),
    number: "9",
    signing: "2024-06-30",
    birthLocation: "Lyon, France",
    position: "Forward",
    height: "185 cm",
    weight: "81 kg",
    gender: "Male",
    status: "Active",
    description: "French professional footballer who plays as a striker.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "karimbenzema",
    twitter: "karimbenzema",
    instagram: "karimbenzema",
  },
  {
    idPlayer: "P003",
    idAPIfootball: "API_P003",
    name: "Robert Lewandowski",
    alternateName: "Robert Lewandowski",
    nationality: "Poland",
    team: "T003",
    sport: "Soccer",
    dateBorn: new Date("1988-08-21"),
    number: "9",
    signing: "2024-06-30",
    birthLocation: "Warsaw, Poland",
    position: "Forward",
    height: "185 cm",
    weight: "81 kg",
    gender: "Male",
    status: "Active",
    description: "Polish professional footballer who plays as a striker.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "rlewa",
    twitter: "lewy_official",
    instagram: "_rl9",
  },
  {
    idPlayer: "P004",
    idAPIfootball: "API_P004",
    name: "Federico Chiesa",
    alternateName: "Federico Chiesa",
    nationality: "Italy",
    team: "T004",
    sport: "Soccer",
    dateBorn: new Date("1997-10-25"),
    number: "7",
    signing: "2024-06-30",
    birthLocation: "Genoa, Italy",
    position: "Winger",
    height: "175 cm",
    weight: "70 kg",
    gender: "Male",
    status: "Active",
    description: "Italian professional footballer who plays as a winger.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "federicochiesa",
    twitter: "federicochiesa",
    instagram: "federicochiesa",
  },
  {
    idPlayer: "P005",
    idAPIfootball: "API_P005",
    name: "Kylian Mbappé",
    alternateName: "Kylian Mbappé Lottin",
    nationality: "France",
    team: "T005",
    sport: "Soccer",
    dateBorn: new Date("1998-12-20"),
    number: "7",
    signing: "2024-06-30",
    birthLocation: "Paris, France",
    position: "Forward",
    height: "178 cm",
    weight: "73 kg",
    gender: "Male",
    status: "Active",
    description: "French professional footballer who plays as a forward.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "kmbappe",
    twitter: "kmbappe",
    instagram: "k.mbappe",
  },
  {
    idPlayer: "P006",
    idAPIfootball: "API_P006",
    name: "Carlos Vela",
    alternateName: "Carlos Alberto Vela Garrido",
    nationality: "Mexico",
    team: "T006",
    sport: "Soccer",
    dateBorn: new Date("1989-03-01"),
    number: "10",
    signing: "2024-06-30",
    birthLocation: "Cancún, Mexico",
    position: "Forward",
    height: "177 cm",
    weight: "66 kg",
    gender: "Male",
    status: "Active",
    description: "Mexican professional footballer who plays as a forward.",
    thumb: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    cutout: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    render: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg",
    facebook: "carlosvela",
    twitter: "carlosvela11",
    instagram: "carlosvela",
  },
];

// Helper functions to get unique countries
export const getUniqueCountries = () => {
  const leagueCountries = mockLeagues.map((league) => league.country);
  const teamCountries = mockTeams.map((team) => team.country);
  const playerNationalities = mockPlayers.map((player) => player.nationality);

  return [...new Set([...leagueCountries, ...teamCountries, ...playerNationalities])].sort();
};

export const getLeagueCountries = () => {
  return [...new Set(mockLeagues.map((league) => league.country))].sort();
};

export const getTeamCountries = () => {
  return [...new Set(mockTeams.map((team) => team.country))].sort();
};

export const getPlayerNationalities = () => {
  return [...new Set(mockPlayers.map((player) => player.nationality))].sort();
};
